In [1]:
import tensorflow as tf
import numpy as np

1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=99)
random_tensor.numpy()

array([[ 98.44995 ,  98.13475 ,  98.4384  ,  99.32401 ,  98.8222  ],
       [ 99.14626 ,  98.724205,  99.475746, 100.80914 ,  98.99398 ],
       [100.745   ,  98.82984 , 100.19659 ,  98.40907 ,  99.08216 ],
       [100.800255, 100.15229 ,  99.1667  ,  99.61637 ,  98.147705],
       [ 96.76249 , 100.23268 ,  99.75576 ,  98.23361 ,  99.34358 ]],
      dtype=float32)

In [3]:
list_random_tensor = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

convert_random_tensor = tf.convert_to_tensor(list_random_tensor)
convert_random_tensor.numpy()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[-1.1053212 , -0.5337032 , -0.70282155, -0.8248136 ,
         -1.7229011 ],
        [ 0.40025976, -0.05440984,  1.6747596 ,  0.9676441 ,
         -0.02181014],
        [-0.46783957, -0.741314  , -0.28194827, -0.5801647 ,
         -0.8188098 ],
        [ 1.0483968 ,  1.2658724 , -0.96203226,  2.0369697 ,
         -0.2631096 ],
        [ 1.0096521 ,  0.28039458, -1.629472  ,  0.05611019,
         -0.7838548 ]],

       [[-0.65902156,  2.039735  , -0.07684287,  0.06438361,
          0.4470851 ],
        [-1.6937996 , -0.91635734, -0.8866027 , -0.672463  ,
         -0.96071   ],
        [ 0.07430616,  2.1330352 ,  1.3413742 , -0.09889074,
         -0.79081684],
        [-1.0927182 , -0.6194207 ,  0.26277953, -2.2262342 ,
         -0.8897241 ],
        [ 0.6895671 , -0.8483094 ,  0.19402425,  1.7007039 ,
          0.6872873 ]],

       [[ 0.6689199 , -1.1495292 ,  0.5792773 ,  0.27640328,
         -0.06564417],
        [-1.5941949 ,  2.0128272 ,  0.06241494,  1.0458615 ,
         -1

In [5]:
slicing[2,2,2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.41025075>

In [6]:
slicing[2]

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.6689199 , -1.1495292 ,  0.5792773 ,  0.27640328, -0.06564417],
       [-1.5941949 ,  2.0128272 ,  0.06241494,  1.0458615 , -1.5728312 ],
       [ 1.2187505 , -0.68857974,  0.41025075, -0.00828455, -1.9592235 ],
       [ 0.7179611 , -0.5801072 ,  0.5143691 ,  0.15416294, -0.9147121 ],
       [ 0.5397737 ,  0.0991725 , -0.63370335,  1.2948807 ,  0.13902326]],
      dtype=float32)>

In [7]:
tf.gather(slicing, indices=[2,2,2]).numpy()

array([[[ 0.6689199 , -1.1495292 ,  0.5792773 ,  0.27640328,
         -0.06564417],
        [-1.5941949 ,  2.0128272 ,  0.06241494,  1.0458615 ,
         -1.5728312 ],
        [ 1.2187505 , -0.68857974,  0.41025075, -0.00828455,
         -1.9592235 ],
        [ 0.7179611 , -0.5801072 ,  0.5143691 ,  0.15416294,
         -0.9147121 ],
        [ 0.5397737 ,  0.0991725 , -0.63370335,  1.2948807 ,
          0.13902326]],

       [[ 0.6689199 , -1.1495292 ,  0.5792773 ,  0.27640328,
         -0.06564417],
        [-1.5941949 ,  2.0128272 ,  0.06241494,  1.0458615 ,
         -1.5728312 ],
        [ 1.2187505 , -0.68857974,  0.41025075, -0.00828455,
         -1.9592235 ],
        [ 0.7179611 , -0.5801072 ,  0.5143691 ,  0.15416294,
         -0.9147121 ],
        [ 0.5397737 ,  0.0991725 , -0.63370335,  1.2948807 ,
          0.13902326]],

       [[ 0.6689199 , -1.1495292 ,  0.5792773 ,  0.27640328,
         -0.06564417],
        [-1.5941949 ,  2.0128272 ,  0.06241494,  1.0458615 ,
         -1

In [8]:
tf.gather_nd(slicing, indices=[[0,2],[1,2],[2,2],[3,2],[4,2]]).numpy()

array([[-0.46783957, -0.741314  , -0.28194827, -0.5801647 , -0.8188098 ],
       [ 0.07430616,  2.1330352 ,  1.3413742 , -0.09889074, -0.79081684],
       [ 1.2187505 , -0.68857974,  0.41025075, -0.00828455, -1.9592235 ],
       [-1.2367251 , -0.6109182 ,  0.0708511 , -0.58018696, -1.1207387 ],
       [ 1.2563078 ,  1.8026695 , -0.4926047 ,  0.11509959,  0.5461489 ]],
      dtype=float32)

In [9]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([-0.28194827,  1.3413742 ,  0.41025075,  0.0708511 , -0.4926047 ],
      dtype=float32)

2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [10]:
list_prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

3. Tampilkan dimensi dari kedua variable tersebut

In [11]:
random_tensor.shape

TensorShape([5, 5])

In [12]:
prime_tensor.shape

TensorShape([5, 5])

4. Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [13]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat :",tf.pow(prime_tensor,random_tensor))
print("\n6. FloorDiv :",tf.math.floordiv(prime_tensor,random_tensor))
print("\n7. FloorMod :",tf.math.floormod(prime_tensor,random_tensor))
print("\n8. Greater :",tf.math.greater(prime_tensor,random_tensor))
print("\n9. Setara :",tf.equal(prime_tensor,random_tensor))
print("\n10. Tidak Setara :",tf.not_equal(prime_tensor,random_tensor))
print("\n11. Greater Equal :",tf.math.greater_equal(prime_tensor,random_tensor))
print("\n12. Less :",tf.math.less(prime_tensor,random_tensor))
print("\n13. Less Equal :",tf.math.less_equal(prime_tensor,random_tensor))
print("\n14. Maximum :",tf.math.maximum(prime_tensor,random_tensor))
print("\n15. Minimum :",tf.math.minimum(prime_tensor,random_tensor))
print("\n16. Kuadrat Perbedaan :",tf.math.squared_difference(prime_tensor,random_tensor))
print("\n17. TrueDiv :",tf.math.truediv(prime_tensor,random_tensor))
print("\n18. XdivY :",tf.math.xdivy(prime_tensor,random_tensor))
print("\n19. Xlog1pY :",tf.math.xlog1py(prime_tensor,random_tensor))
print("\n20. XlogY :",tf.math.xlogy(prime_tensor,random_tensor))
print("\n21. Atan2 :",tf.math.atan2(prime_tensor,random_tensor))

1. Penjumlahan : tf.Tensor(
[[100.44995  101.13475  103.4384   106.32401  109.8222  ]
 [112.14626  115.724205 118.475746 123.80914  127.99398 ]
 [131.745    135.82983  141.1966   141.40907  146.08215 ]
 [153.80026  159.15228  160.1667   170.61636  171.1477  ]
 [175.76248  183.23268  188.75577  195.23361  100.34358 ]], shape=(5, 5), dtype=float32)

2. Pengurangan : tf.Tensor(
[[-96.44995   -95.13475   -93.4384    -92.32401   -87.8222   ]
 [-86.14626   -81.724205  -80.475746  -77.80914   -69.99398  ]
 [-69.745     -61.82984   -59.196587  -55.409073  -52.08216  ]
 [-47.800255  -41.15229   -38.166702  -28.616371  -25.147705 ]
 [-17.76249   -17.232681  -10.75576    -1.2336121 -98.34358  ]], shape=(5, 5), dtype=float32)

3. Perkalian : tf.Tensor(
[[ 196.8999   294.40424  492.19202  695.26807 1087.0442 ]
 [1288.9014  1678.3115  1890.0392  2318.6104  2870.8254 ]
 [3123.095   3656.704   4108.06    4231.5903  4656.8613 ]
 [5342.4136  5908.9854  6049.169   7072.762   7164.782  ]
 [7644.237   8319

5. Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [14]:
tf.argmax(random_tensor, axis=0).numpy()#max baris random_tensor

array([3, 4, 2, 1, 4], dtype=int64)

In [15]:
tf.argmax(random_tensor, axis=1).numpy()#max kolom random_tensor

array([3, 3, 0, 0, 1], dtype=int64)

In [16]:
tf.argmin(random_tensor, axis=0).numpy()#min baris random_tensor

array([4, 0, 0, 4, 3], dtype=int64)

In [17]:
tf.argmin(random_tensor, axis=1).numpy()#min kolom random_tensor

array([1, 1, 3, 4, 0], dtype=int64)

6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [18]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()#penggabungan baris

array([[ 98.44995 ,  98.13475 ,  98.4384  ,  99.32401 ,  98.8222  ],
       [ 99.14626 ,  98.724205,  99.475746, 100.80914 ,  98.99398 ],
       [100.745   ,  98.82984 , 100.19659 ,  98.40907 ,  99.08216 ],
       [100.800255, 100.15229 ,  99.1667  ,  99.61637 ,  98.147705],
       [ 96.76249 , 100.23268 ,  99.75576 ,  98.23361 ,  99.34358 ],
       [  2.      ,   3.      ,   5.      ,   7.      ,  11.      ],
       [ 13.      ,  17.      ,  19.      ,  23.      ,  29.      ],
       [ 31.      ,  37.      ,  41.      ,  43.      ,  47.      ],
       [ 53.      ,  59.      ,  61.      ,  71.      ,  73.      ],
       [ 79.      ,  83.      ,  89.      ,  97.      ,   1.      ]],
      dtype=float32)

In [19]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()#penggabungan 

array([[ 98.44995 ,  98.13475 ,  98.4384  ,  99.32401 ,  98.8222  ,
          2.      ,   3.      ,   5.      ,   7.      ,  11.      ],
       [ 99.14626 ,  98.724205,  99.475746, 100.80914 ,  98.99398 ,
         13.      ,  17.      ,  19.      ,  23.      ,  29.      ],
       [100.745   ,  98.82984 , 100.19659 ,  98.40907 ,  99.08216 ,
         31.      ,  37.      ,  41.      ,  43.      ,  47.      ],
       [100.800255, 100.15229 ,  99.1667  ,  99.61637 ,  98.147705,
         53.      ,  59.      ,  61.      ,  71.      ,  73.      ],
       [ 96.76249 , 100.23268 ,  99.75576 ,  98.23361 ,  99.34358 ,
         79.      ,  83.      ,  89.      ,  97.      ,   1.      ]],
      dtype=float32)

7. Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [20]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 99.32401 ,  98.8222  ,  98.44995 ,  98.4384  ,  98.13475 ],
       [100.80914 ,  99.475746,  99.14626 ,  98.99398 ,  98.724205],
       [100.745   , 100.19659 ,  99.08216 ,  98.82984 ,  98.40907 ],
       [100.800255, 100.15229 ,  99.61637 ,  99.1667  ,  98.147705],
       [100.23268 ,  99.75576 ,  99.34358 ,  98.23361 ,  96.76249 ]],
      dtype=float32)

In [21]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[3, 4, 0, 2, 1],
       [3, 2, 0, 4, 1],
       [0, 2, 4, 1, 3],
       [0, 1, 3, 2, 4],
       [1, 2, 4, 3, 0]])

In [22]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [23]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])